replicas: 1

image:
  repository: mcr.microsoft.com/mssql/server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2019-latest"

ACCEPT_EULA:
  value: "y"
MSSQL_PID:
  value: "Developer"
MSSQL_AGENT_ENABLED:
  value: "true"
hostname: mssqllatest
sa_password: "Toughpass1!"
containers:
  ports:
    containerPort: 1433

podAnnotations: {}

podSecurityContext:
  fsGroup: 10001

service:
  type: ClusterIP
  port: 1433

pvc:
  enabled: false
  storageClassName: ""
  userdbsize: 5Gi
  userlogsize: 5Gi
  tempsize: 2Gi
  mssqldbsize: 2Gi


